### ISSUE TITLE
Delete comment from forum post

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#128]
Create controller function to delete comment from the forum post

**Comment by Nikhil-dev13** [comment]
I would like to work in this issue

**Comment by gauravdas014** [comment]
Are you a part of GSSoC extended @Nikhil-dev13 ? This project is currently only for GSSoC extended participants.

**Comment by Nikhil-dev13** [comment]
Sorry I didn't knew

**Comment by Shubham-1105** [comment]
I want to work on this
