### ISSUE TITLE
User authentication : Login

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#13]
Make the user login system. Don't use passport js. Use login system built from scratch.

**Comment by joharikushagra** [comment]
I can work on this

**Comment by tripathyprateek** [comment]
If no one is assigned, I would like to work on this. But this requires completion of previous tasks of Database schema and Signup demo ready.

**Comment by gauravdas014** [comment]
@tripathyprateek  I am assigning you this task. Do this once the signup is done

**Comment by nanda-mik** [comment]
i can contribute this!

**Comment by nanda-mik** [comment]
Yes i would like to work on reset-password functionality!

**Comment by gauravdas014** [comment]
Let me assign you.

**Comment by gauravdas014** [comment]
@nanda-mik Comment on the issue I just created

**Comment by gauravdas014** [comment]
@tripathyprateek It's been a long time you were assigned this task. Need any help?

**Comment by tripathyprateek** [comment]
Hi sorry I have been a bit busy. I was waiting for the database to be defined and then I haven't looked up at the project. I will just unassign myself for this issue and pick up another one when time permits. Really sorry.

**Comment by gauravdas014** [comment]
okay no problem. Thanks for informing.

**Comment by joharikushagra** [comment]
I can work on this
