### ISSUE TITLE
Get Feed for the forum 

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#130]
Create a controller function to make the feed for the forum and display it to the user. Paginate the no of results to 20.

**Comment by subhangi2731** [comment]
please assign me this

**Comment by gauravdas014** [comment]
@subhangi2731 Can you explain how you are going to implement it?

**Comment by pkspyder007** [comment]
@subhangi2731 Are you still interested in working on this issue?

**Comment by gauravdas014** [comment]
@pkspyder007 currently she is working on another issue.

**Comment by piyushsharma21** [comment]
@pkspyder007 If this issue is unassigned, please consider assigning to me

**Comment by subhangi2731** [comment]
I want to work on this please assign me @pkspyder007 I will share u the implementation within  2 days

**Comment by subhangi2731** [comment]
@gauravdas014 @pkspyder007 can u plesse guide me on how will I start for this and what exactly I have to do and using what??

**Comment by gauravdas014** [comment]
@subhangi2731 We don't need this as of now. Therefore I am closing the issue.
