### ISSUE TITLE
Tag the user in the comments of forum post

### ISSUE THREAD

**Issue by Nikunj-Aggarwal** [girlscript/feminist-bible-phase-2#136]
Create a controller function to tag the users in the comments of forum post.

**Comment by RituCs** [comment]
Hey , I want to work on this issue.Please guide me further.

**Comment by HelenEH0** [comment]
@Nikunj-Aggarwal,
I also want to work on this project as a beginner GSSOC'21 participant. Please assign and guide me through this project.
