### ISSUE TITLE
Create a Forum Post Component. 

### ISSUE THREAD

**Issue by salil-naik** [girlscript/feminist-bible-phase-2#143]
- [ ] Refer to the Figma design. 
- [ ] Use SVGs for like, comment and social media icons.
- [ ] Make it responsive. Use correct breakpoints for media queries.
- [ ] Refrain from using fixed widths and heights. 
- [ ] Use existing components wherever necessary.

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by inomag** [comment]
Is the issue open?

**Comment by salil-naik** [comment]
@inomag 1 dev is already working on it. : )

**Comment by salil-naik** [comment]
@Shubham-1105 Please continue with this.
