### ISSUE TITLE
Create a blog-card component

### ISSUE THREAD

**Issue by salil-naik** [girlscript/feminist-bible-phase-2#15]
Kindly refer to the design and make the blog card. All the dimensions should be pixel perfect. User variables wherever necessary.

**Comment by sonali-singh97** [comment]
I would like to work on this issue.

**Comment by salil-naik** [comment]
This issue is solved
https://github.com/girlscript/feminist-bible-phase-2/commit/8e3af1bc8a00d79295ab7d72c9fdffd5f758c56b
