### ISSUE TITLE
Update auth controller to set error status on response if user exists

### ISSUE THREAD

**Issue by pkspyder007** [girlscript/feminist-bible-phase-2#160]
The current signup method in authController does not return a bad request on a user that already exists check.
I would like to work on this quick fix @gauravdas014

**Comment by gauravdas014** [comment]
Please go ahead @pkspyder007

**Comment by gauravdas014** [comment]
@pkspyder007 This issue should be closed right?

**Comment by pkspyder007** [comment]
Yes it is fixed
