### ISSUE TITLE
Use http-only cookie for jwt token

### ISSUE THREAD

**Issue by pkspyder007** [girlscript/feminist-bible-phase-2#168]
The current implementation of JWT lets the frontend to manage the JWT token on the client-side, which can store jwt in localStorage, etc.
This could be a security issue.
To tackle this, the backend API should attach the JWT token to an HTTP-only cookie so that the frontend or any other client-side js is not able to extract the token

**Comment by joharikushagra** [comment]
I would like to do this

**Comment by gauravdas014** [comment]
@joharikushagra sorry for the delay in replying. Would you still like to work on this issue?

**Comment by subhangi2731** [comment]
hey please i want to work on this please assign me

**Comment by gauravdas014** [comment]
@subhangi2731 I am assigning this issue. Please make sure you read the contributing guidelines before contributing. Write tests if required and make sure no test cases are failing.

**Comment by gauravdas014** [comment]
@subhangi2731 What's the status?

**Comment by pkspyder007** [comment]
@gauravdas014 you may assign this to someone else.

**Comment by gauravdas014** [comment]
> @gauravdas014 you may assign this to someone else.

Yes, sure!

**Comment by subhangi2731** [comment]
I have worked on this @gauravdas014 will send the pr by tommorrow. Please reassign me I was out of station for a few days so I was not able to communicate

**Comment by gauravdas014** [comment]
@subhangi2731 Please give the PR by tomorrow.

**Comment by gauravdas014** [comment]
> I have worked on this @gauravdas014 will send the pr by tommorrow. Please reassign me I was out of station for a few days so I was not able to communicate

Okay, no issue!

**Comment by subhangi2731** [comment]
> > I have worked on this @gauravdas014 will send the pr by tommorrow. Please reassign me I was out of station for a few days so I was not able to communicate
> 
> Okay, no issue!



> @subhangi2731 Please give the PR by tomorrow.

Okay sure, Thanks

**Comment by gauravdas014** [comment]
@subhangi2731 Have you completed the task?

**Comment by subhangi2731** [comment]
@gauravdas014 I need little more time will send the pr by tomorrow can u please give me one more day?

**Comment by gauravdas014** [comment]
@subhangi2731 okay, it's fine if you send PR by tomorrow. @shashankmotruri @nanda-mik. Please help her. She is facing some issues.

**Comment by jhasuraj01** [comment]
I would like to work on this issue, I also have practical experience regardless this issue

**Comment by gauravdas014** [comment]
@jhasuraj01 Please go ahead

**Comment by jhasuraj01** [comment]
> @jhasuraj01 Please go ahead

Thanks, will update you soon

**Comment by jhasuraj01** [comment]
@gauravdas014 I have made necessary changes in `backend\controllers\authController.js` shall I make a PR?

**Comment by gauravdas014** [comment]
@jhasuraj01  Sure!
