### ISSUE TITLE
Make a footer component.

### ISSUE THREAD

**Issue by salil-naik** [girlscript/feminist-bible-phase-2#17]
Kindly refer to the design and make the footer. All the dimensions should be pixel perfect. Use scss variables wherever necessary.

**Comment by m-code12** [comment]
I would like to take this up.

**Comment by joharikushagra** [comment]
I want to work on this

**Comment by Shubham-1105** [comment]
I would want to work on this

**Comment by m-code12** [comment]
@salil-naik I was the first one to claim this issue. Also, I haven't made my contribution to this repo. So, it would be great if you could assign me.

**Comment by salil-naik** [comment]
@m-code12  I appreciate your enthusiasm to work on this issue. But this issue is assigned to some other participant.

In the frontend, the tasks are distributed beforehand to the participants so that everyone gets a fair chance to contribute.

We are communicating over a WhatsApp group. If you are interested in contributing to the frontend, kindly ping me on slack.
