### ISSUE TITLE
Add a favicon.

### ISSUE THREAD

**Issue by padmajabhol** [girlscript/feminist-bible-phase-2#207]
I want to add a theme based favicon. Can you assign it to me?

**Comment by thesakshipandey** [comment]
I have good resources to work on this issue,
can you assign this issue to me under GSSoC'21?

**Comment by shivangi942** [comment]
I want to work in this issue. Can you please assign it to me?

**Comment by pkspyder007** [comment]
Why do you think this is needed? @padmajabhol

**Comment by DeeptiTeragunti** [comment]
I would like to work on this issue.Can i be assigned with this piece of work?

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by gauravdas014** [comment]
We already have a favicon. So this issue makes no sense, therefore closing the issue.
