### ISSUE TITLE
Sticky navbar.

### ISSUE THREAD

**Issue by padmajabhol** [girlscript/feminist-bible-phase-2#208]
I want to fix the top navbar. Please assign me.

**Comment by muskaan-ag09** [comment]
Please assign me this issue. I would be like to contribute.

**Comment by gauravdas014** [comment]
@padmajabhol can you attach of a screenshot of what you want to fix?

**Comment by ManuGupta9780** [comment]
Currently, the navbar is not sticky,i.e it does not stays on top of the user's browser as we scroll down. Fixed top navbar provides a better UI.
I would like to change it in the following way:

![scroll1](https://user-images.githubusercontent.com/59606099/111040886-6f5a2080-845b-11eb-9c26-5816a744694b.png)

Navbar stays on top on scrolling down.

![scroll2](https://user-images.githubusercontent.com/59606099/111040890-741ed480-845b-11eb-95c2-7188fadb87fc.png)

@gauravdas014  I would like to contribute to this issue as a participant of GSSOC21. Please assign this issue to me.

**Comment by gauravdas014** [comment]
@ManuGupta9780 Work on the issue, I am assigning.
