### ISSUE TITLE
Make Changes in contributing.md

### ISSUE THREAD

**Issue by khareyash05** [girlscript/feminist-bible-phase-2#209]
Hi @salil-naik @gauravdas014 @pkspyder007  I would like to make changes and update contributing.md . I will mention steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forkedrepo as well as local repo as the changes are made to the upstream

I would like to work on it as a part of GSSOC'21

**Comment by gauravdas014** [comment]
@khareyash05 show us what you want to change!

**Comment by khareyash05** [comment]
I will mention steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forked repo as well as local repo as the changes are made to the upstream

**Comment by gauravdas014** [comment]
Great! Please proceed with the changes and give a PR when done.
