### ISSUE TITLE
fix Footer Navigation Error!! 🚀🚀

### ISSUE THREAD

**Issue by bhubesh757** [girlscript/feminist-bible-phase-2#211]
@pkspyder007 If We press the Button in Footer it actually navigates to particular url  http://localhost:3000/placeholder  , 

https://user-images.githubusercontent.com/55022929/110803080-d71a3b00-82a4-11eb-83e2-8f534c089f05.mp4

**Comment by ShreyashRoyzada** [comment]
Hello I would like to work on this issue as part of GSSOC21. Can you please assign this to me.?
Thank you.

**Comment by bhubesh757** [comment]
@ShreyashRoyzada  Yes I will Work on this Issue , Kindly , Assign this to me!
