### ISSUE TITLE
chore(update): missing bug_report and feature request template

### ISSUE THREAD

**Issue by Uyadav207** [girlscript/feminist-bible-phase-2#212]
**Need**?

- Important according to OSS guidelines.
- Help maintainer to differentiate a `bug` `feature`, `feature(already included in the project)`

Hey Maintainer!
I want to work on creating an effective template for bug and feature requests.
Please assign me the task. (**For GGSOC'21**)

**Comment by gauravdas014** [comment]
@Uyadav207 Go for it.

**Comment by Uyadav207** [comment]
@gauravdas014 Thanks

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by Uyadav207** [comment]
> hello
> 
> i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

@amritakesh This is no more an issue now... The required PR has been already merged... Please try out some other issue... to contribute on.
