### ISSUE TITLE
fix : login-page__illustration size

### ISSUE THREAD

**Issue by shashankmotruri** [girlscript/feminist-bible-phase-2#225]
<img src="https://user-images.githubusercontent.com/56257201/111520064-bc046b00-877d-11eb-9228-ab370c7bb516.png"  width=40% height=40%/>
<img src="https://user-images.githubusercontent.com/56257201/111520074-be66c500-877d-11eb-9339-054ae830a884.png" width=40% height=40%/>

**Comment by prajakta2809** [comment]
can you assign this to me.I would like to work on this.

**Comment by joharikushagra** [comment]
I would like to work on it
