### ISSUE TITLE
Dockerizing the setup as an alternative for installation!

### ISSUE THREAD

**Issue by jain-rishabh-21** [girlscript/feminist-bible-phase-2#226]
### **Is your feature request related to a problem? Please Describe.**

WIll solve the problem regarding setup for developers working on different OS.

### **Describe the solution you'd like**

Using docker for simplifying the installation

### **Describe alternatives you've considered**

NA

### **Additional context**

NA

**Comment by jain-rishabh-21** [comment]
If found useful , please assign it to me.
Discord: krackerzzz#4371

**Comment by shashankmotruri** [comment]
@jain-rishabh-21 As of now it is not necessary. Our primary goal is to complete the api and react app. So I'm closing this issue.
