### ISSUE TITLE
Add package-lock.json to .gitignore

### ISSUE THREAD

**Issue by pkspyder007** [girlscript/feminist-bible-phase-2#228]
The lock files are creating unnecessary error/merge conflicts.
Adding these files to .gitignore will solve this

**Comment by Devenkapoor7303** [comment]
Can I work on this issue as a GSSOC participant

**Comment by KaranKaira** [comment]
I would like to work on this issue as a GSSOC participant

**Comment by kumarishalini6** [comment]
@pkspyder007  can you allow me to work on this issue , I have experience to add into .gitignore .

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by kumarishalini6** [comment]
i have send PR but i guess there is some issue please check it and let me know the problems .

**Comment by pkspyder007** [comment]
I am  closing this issue as this is producing errors during the checks and version mismatch
