### ISSUE TITLE
Shifting from classes to functional components

### ISSUE THREAD

**Issue by KaranKaira** [girlscript/feminist-bible-phase-2#229]
### **Is your feature request related to a problem? Please Describe.**

Many components are class components.

### **Describe the solution you'd like**

I want to convert all class components to functional components.

### **Describe alternatives you've considered**
NA

### **Additional context**

NA

**Comment by shashankmotruri** [comment]
@KaranKaira changing class comps to  functions will be lots of trouble, as state management need to be considered . So I'm closing this issue. Feel free to comment : )

**Comment by KaranKaira** [comment]
True .
What if I can make a branch with class components replaced with functional component ?? 
Development in both branches can move parallelly.Contributors can work on both branches. .
Bcoz ,eventually we must move towards functional components .

And when this branch is up to date with the master branch ,then we can shift entirely to functional components.

Would like to hear suggestions..

**Comment by pkspyder007** [comment]
@KaranKaira that sounds feasible. Come out with a proper plan and contribution guide for this issue.
