### ISSUE TITLE
Work on reset password functionality.

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#25]
Use bcrypt js for encrypting the password. Use nodemailer to send the reset password email. On clicking the link user will have the option to enter new password and confirm password. Encrypt the password and save it to database. Let the user schema be created first then work on this

**Comment by Shubham-1105** [comment]
I am working on the user schema,so i can implement it.

**Comment by gauravdas014** [comment]
One participant has already told me that he wants to work on this issue. So I won't be able to assign you this issue. Don't worry I will assign some other issue

**Comment by nanda-mik** [comment]
I will contribute to the reset-password functionality!
