### ISSUE TITLE
Add Welcome bot

### ISSUE THREAD

**Issue by itsIapetus** [girlscript/feminist-bible-phase-2#253]
### **Is your feature request related to a problem? Please Describe.**

I would like to add a welcome bot, for new issues, PRs, etc.
Kindly assign it to me under gssoc, thanks!

**Comment by pkspyder007** [comment]
@itsIapetus I don't get a point what you are trying to achieve. Please explain a bit more?

**Comment by pkspyder007** [comment]
I am closing this issue as it is not useful to the project right now.
