### ISSUE TITLE
Tests for APIs are missing

### ISSUE THREAD

**Issue by singhayushh** [girlscript/feminist-bible-phase-2#254]
Hello, 
The tests for various api endpoints are missing currently.
Since there are a lot of endpoints, it'd be better if they are broken into separate issues - one for each
- user
- story
- project
- org
- forum
- auth
- admin

I am willing to work on this issue myself.

**Comment by pkspyder007** [comment]
@singhayushh  Please connect with @gauravdas014 to complete this task. He can guide to if you have any doubts. 👍

**Comment by gauravdas014** [comment]
@singhayushh Let the Issue be a single issue, you can create multiple PRs or a single pr with subtasks, whatever you prefer. On completion of all the sub-issues under this issue, I will close this issue. React out for any other clarification

**Comment by gauravdas014** [comment]
@singhayushh Are you working on it?

**Comment by singhayushh** [comment]
@gauravdas014 
I've been having exams in college and I couldn't work on it..

**Comment by gauravdas014** [comment]
@singhayushh May I unassign you or you would like to work in a couple of days?

**Comment by singhayushh** [comment]
Can we break it into multiple assignees?
I'll write tests for say, user and admin routes
Someone else continues the tests for other routes?

**Comment by gauravdas014** [comment]
@singhayushh That's also fine. You can directly give PR, just mention that PR is a part of this issue. Or you can create a separate issues also.

**Comment by singhayushh** [comment]
Hey, sorry to inform but I'm unable to give enough time to the issue rn. I'd opt to be unassigned for now and let others work on this. 

Sorry for the inconvenience, if caused.

**Comment by gauravdas014** [comment]
> Hey, sorry to inform but I'm unable to give enough time to the issue rn. I'd opt to be unassigned for now and let others work on this.
> 
> Sorry for the inconvenience, if caused.

That's fine.

**Comment by subhangi2731** [comment]
please assign me this.

**Comment by gauravdas014** [comment]
@subhangi2731 Please explain how you will proceed? What tools of testing you are planning to use?

**Comment by subhangi2731** [comment]
I will use postman to test API endpoints or the citrus as I am familiar with them

**Comment by gauravdas014** [comment]
@subhangi2731 Have you used `supertest` before? It is used for API testing

**Comment by subhangi2731** [comment]
yes I have It is used to test HTTP endpoints and for that we need supertest module and install its dependecies

**Comment by gauravdas014** [comment]
@subhangi2731 go ahead with the issue. First, write tests for the users and give PR. After its reviewed please continue with the rest

**Comment by subhangi2731** [comment]
sure @gauravdas014

**Comment by subhangi2731** [comment]
@gauravdas014 can u please reply so that i can send a pr

**Comment by gauravdas014** [comment]
> @gauravdas014 since there are a lot of endpoints to cover all should come under one issue then what endpoints should I test??can u be more specific.

You have to write tests for all the endpoints.

**Comment by subhangi2731** [comment]
okay done

**Comment by subhangi2731** [comment]
@gauravdas014 https://github.com/girlscript/feminist-bible-phase-2/blob/master/backend/.env.example in this how to bring all these four??
JWT_EXPIRES_IN=JWT expiry time
JWT_SECRET=JWT Secret
JWT_COOKIE_EXPIRES_IN=cookie expiry time
JWT_COOKIE_DOMAIN=.example.com

**Comment by subhangi2731** [comment]
@gauravdas014 please help so that I can make a pr

**Comment by singhayushh** [comment]
@subhangi2731 

JWT_EXPIRES_IN=86400000
JWT_SECRET=123xyz.xyz123
JWT_COOKIE_EXPIRES_IN=8640000
JWT_COOKIE_DOMAIN=http://localhost

**Comment by subhangi2731** [comment]
@gauravdas014 @singhayushh while doing npm run dev http://localhost:8080/api/user
this is coming Unauthorized why please tell me

**Comment by singhayushh** [comment]
@subhangi2731 
The route requires the request to be coming from an authenticated user
So you need to first hit the login / sign in route and then use these routes.

**Comment by subhangi2731** [comment]
@singhayushh @gauravdas014 how to authorize and where is the signup route

**Comment by subhangi2731** [comment]
can u please tell me in detail @singhayushh

**Comment by gauravdas014** [comment]
> @singhayushh @gauravdas014 how to authorize and where is the signup route

Please check the api-docs for the required routes. The sign up route is in authRoutes.js

**Comment by subhangi2731** [comment]
ok @gauravdas014 what ill be the endpoint for signing up in this route

**Comment by singhayushh** [comment]
@subhangi2731 please go through the code. Just knowing the endpoint isn't enough.

**Comment by subhangi2731** [comment]
![IMG-20210520-WA0018](https://user-images.githubusercontent.com/53938490/119004447-3767e000-b9ac-11eb-8283-0e54cd961626.jpg)
![IMG-20210520-WA0018 (1)](https://user-images.githubusercontent.com/53938490/119004478-3df65780-b9ac-11eb-99a1-caa6a6c4cb03.jpg)

**Comment by subhangi2731** [comment]
@gauravdas014 please check signup is not happening by any route

**Comment by singhayushh** [comment]
@subhangi2731 it's a post request and not a get request. Please go through the code thoroughly before writing tests.
