### ISSUE TITLE
Adding Hover Effect to Cards

### ISSUE THREAD

**Issue by iampranavdhar** [girlscript/feminist-bible-phase-2#257]
Hey!
I am Pranavdhar. I hope to add hover effects to the cards of organization, blog, and project which makes it look more appealing. If you wish to add this feature consider assigning it to me.
Thanks

**Comment by gauravdas014** [comment]
@pkspyder007 Considering the design we have, do we have any such plan?

**Comment by pkspyder007** [comment]
Yes that could be nice small touch 👍

**Comment by iampranavdhar** [comment]
So, can you assign it to me and assign a gssoc label. @pkspyder007 @gauravdas014

**Comment by soulsurya** [comment]
Hello!
I'm Suryakant i wish to make your site more appealing and stylish by adding hover effects on various card components,i have a good css experience would you like to give me a chance?

**Comment by iampranavdhar** [comment]
Yeah, thanks @shashankmotruri  will work on it and notify you once it's done.

**Comment by ankan10** [comment]
Can I work on it?

**Comment by gauravdas014** [comment]
> Can I work on it?

As you can see this issue is already assigned. Please comment on some other issue, or you can open new issues!
