### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by sonal251001** [girlscript/feminist-bible-phase-2#258]
### **Is your feature request related to a problem? Please Describe.**

In the README.md we could add a table to list all the open source organizations this project has been part of. For example GSSoC , Winter of code , etc.

**Comment by shashankmotruri** [comment]
@sonal251001 please can you explain a bit more on what u r going to achieve ?

**Comment by sonal251001** [comment]
I thought of making a table listing all the open-source organizations that this project has been a part of like I saw this in one of the projects I can't find it now. It will look as like this in the README.md

**List of open-source programs**

1)GSSoC - 2021
2).............(If any other organizations you know the project was a part of)
