### ISSUE TITLE
Separate env files for production and development

### ISSUE THREAD

**Issue by singhayushh** [girlscript/feminist-bible-phase-2#260]
It's a good practice to have separate env files for development and production. The project's backend is to have tests for routes which cannot be done in the production database.

#### Proposal:
- having two env files instead of one, named `env.production` and `env.development`.
- using [cross-env](https://www.npmjs.com/package/cross-env), we can set an environment variable with each script (npm start, npm test etc) to denote whether the script is to be used in production or in development.

#### Changes to be done
- installing and configuring the cross-env package for every script
- updating all dotenv.config calls to include either the production or the development env file based on the environment variable passed
- updating all documentations that mention of the .env file

**Comment by piyushsharma21** [comment]
Hello @singhayushh , as part of GSSOC21, I would love to work on this issue, if still unresolved please consider assigning to me. 
Thanks
