### ISSUE TITLE
Add the website icon in title bar

### ISSUE THREAD

**Issue by Shubhrima** [girlscript/feminist-bible-phase-2#265]
### **Is your feature request related to a problem? Please Describe.**
No logo in the tab displayed in the title bar.

### **Describe the solution you'd like**
The logo is the visual representation of the organization, and the website icon plays important role in helping the organization to stand out.

Add the website icon in the tab of the title bar
### **Additional context**

![image](https://user-images.githubusercontent.com/68013183/112574176-cd034b00-8e13-11eb-9cc8-4d3a8e21da1f.png)
![image](https://user-images.githubusercontent.com/68013183/112574141-b78e2100-8e13-11eb-8435-9ae9235d4a46.png)

**Comment by Sourav61** [comment]
Could you please assign me this?

**Comment by Shubhrima** [comment]
Hi, @Sourav61 I  myself am a GSSOC'21 participant and want to work on this. :)

**Comment by Sourav61** [comment]
okay

**Comment by gauravdas014** [comment]
@Shubhrima There is a favicon already. Can you please check in other browser
