### ISSUE TITLE
Adding custom dialog box

### ISSUE THREAD

**Issue by Alenjojo** [girlscript/feminist-bible-phase-2#266]
### **Is your feature request related to a problem? Please Describe.**

The dialog boxes that shows are the basic ones which are inbuilt. Those doesn't match the current user experience

### **Describe the solution you'd like**

I can make a custom dialog box with displays messages or selection accordingly

So can you assign this issue to me

**Comment by shashankmotruri** [comment]
@Alenjojo Can you elaborate more on what you want to accoplish?

**Comment by gauravdas014** [comment]
This was inactive for a long time. So I closed.
