### ISSUE TITLE
validator is missing

### ISSUE THREAD

**Issue by himanshujaidka** [girlscript/feminist-bible-phase-2#267]
isSignin() function should be there inside the validator folder, I would be happy if this issue will assigned to me

**Comment by gauravdas014** [comment]
@himanshujaidka In the authController there is already a isSignin() function. Are you talking about this only?

**Comment by himanshujaidka** [comment]
yes, I think that function should be inside validator

**Comment by gauravdas014** [comment]
That's an auth middleware, it's fine to keep it in authController.

**Comment by himanshujaidka** [comment]
ok
