### ISSUE TITLE
Add comments to the routes and controllers in the backend API

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#268]

**Comment by GurshehzadSingh** [comment]
im a gssoc participant and i would like to work on this isuue.

**Comment by gauravdas014** [comment]
@GurshehzadSingh Please go ahead. Make sure you read the contributing guidelines before contributing.

**Comment by GurshehzadSingh** [comment]
I will be sending the PR tomorrow for this issue.

**Comment by gauravdas014** [comment]
@GurshehzadSingh okay !

**Comment by GurshehzadSingh** [comment]
I have completed all requirements. Kindly review and merge the PR. Thanks for the opportunity!
