### ISSUE TITLE
feat : 404 error page 

### ISSUE THREAD

**Issue by shashankmotruri** [girlscript/feminist-bible-phase-2#276]
- Make sure header and footer are included.

**Comment by EANimesha** [comment]
I am gssoc participant. Can I work on this issue?

**Comment by raks924** [comment]
i want to work on this issue. Kindly assign me this issue.

**Comment by shitesh2607** [comment]
I'm working on this issue.

**Comment by shashankmotruri** [comment]
@EANimesha Any Update?

**Comment by EANimesha** [comment]
will give update by today
