### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by mansijain980** [girlscript/feminist-bible-phase-2#277]
Update Readme with some gifs and emojis and to start development mode we can add commands in readme.
Please assign it to me.

**Comment by shashankmotruri** [comment]
@mansijain980 For how to start the project is already mentioned in contributing.md . .

**Comment by mansijain980** [comment]
@shashankmotruri yes sir bt i thought it is looking simple so it can be attractive with gifs nd all.

**Comment by raks924** [comment]
can i work on this issue?
