### ISSUE TITLE
Correction of spellings, grammatical and punctuation errors in the README.md

### ISSUE THREAD

**Issue by sarala-2210** [girlscript/feminist-bible-phase-2#281]
Hello mentors , I would like to correct some of the spellings, grammatical and punctuation errors in the README.md. Looking forward to working on this issue as a GSSOC 21 participant. Thank you:)

**Comment by gauravdas014** [comment]
@sarala-2210 can you show the errors? Screenshots may be!

**Comment by sarala-2210** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/52791971/112973528-11258100-916f-11eb-9e9c-608198cbb090.png)
@gauravdas014 and some more minor changes like, 
bugfixes->bug fixes 
bugs which have ->bugs that have
voices from -> voices of
diversity centric -> diversity-centric
 To Add: DEI means Diversity Equity & Inclusion

**Comment by gauravdas014** [comment]
@sarala-2210 Go Ahead
