### ISSUE TITLE
Activation of DeepSource

### ISSUE THREAD

**Issue by HarshCasper** [girlscript/feminist-bible-phase-2#286]
Hi 👋 

One of my Pull Requests around fixing Code Quality Issues with DeepSource was merged here: https://github.com/girlscript/feminist-bible-phase-2/pull/206

I'd just like to inform you that the issues fixed here were detected by running DeepSource analysis on the repo. If you like, you can activate analysis for your repository to detect such code quality issues/bug risks on the fly for every change made. You can also use the Autofix feature to fix them with one click.

The `.deepsource.toml` file you merged will only take effect if you activate analysis for this repo.

Here's what you can do if you wish to activate DeepSource to continuously analyze your repository:

- [Sign up](https://deepsource.io/signup) on DeepSource and activate analysis for this repository.
- Create `.deepsource.toml` configuration which you can use to configure your analysis settings (My PR already added that, but feel free to edit it anytime).
- Track/Check analysis [here](http://deepsource.io/gh/girlscript/feminist-bible-phase-2/).

If you have any doubts or questions, you can check out the [docs](https://deepsource.io/docs/), or feel free to reach out :)

**Comment by gauravdas014** [comment]
Hi @HarshCasper! for activating DeepSource admin's approval is required. This repository is a part of the GirlScript Foundation Organization. So, it may take some time to get the request approved by the owner.

**Comment by HarshCasper** [comment]
> Hi @HarshCasper! for activating DeepSource admin's approval is required. This repository is a part of the GirlScript Foundation Organization. So, it may take some time to get the request approved by the owner.

Sure. Please let me know if any help would be needed.
