### ISSUE TITLE
Add create story controller function

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#29]
Under controllers directory in userController create a function to create a story . (It's for the scenario when users will write some story (post) ). Add a route and link this to the controller function. Please attach a screenshot of the response in the PR ( Test in postman)

**Comment by pratikbaid3** [comment]
I can work on this

**Comment by gauravdas014** [comment]
@pratikbaid3  It's been a long time you were assigned this task. Need any help?

**Comment by pratikbaid3** [comment]
#79
