### ISSUE TITLE
Feat: Validate cookies before accessing protected routes

### ISSUE THREAD

**Issue by jhasuraj01** [girlscript/feminist-bible-phase-2#294]
### **Problem**
Cookies are not validated before accessing the protected path

### **Solution**
Create a Middleware which will validate the cookies first with each request coming to ```/api/secure/*``` before giving access to private routes
```javascript
app.use('/api/auth', authRouter);
app.use('/api/secure/story', storyRouter);
app.use('/api/secure/org', orgRouter);
app.use('/api/secure/admin', adminRouter);
app.use('/api/secure/user', userRouter);
app.use('/api/secure/project', projectRouter);
app.use('/api/secure/forum', forumRouter);
```

### **Additional context**
I am a GSSoC participant and I would like to work on this issue

**Comment by gauravdas014** [comment]
@jhasuraj01 Instead of using /secure it's better to use a middleware that will verify this.

**Comment by jhasuraj01** [comment]
Okay I would try implementing in other way

**Comment by gauravdas014** [comment]
@jhasuraj01. Make a middleware function and attach it to the routes
