### ISSUE TITLE
Linkedin profile links to open in new tab

### ISSUE THREAD

**Issue by akshay1027** [girlscript/feminist-bible-phase-2#295]
### **Is your feature request related to a problem? Please Describe.**
Linkedin profile links to open in new tab so that its easier for user to come back to codebase!

**Comment by gauravdas014** [comment]
@akshay1027 You can give the PR.

**Comment by akshay1027** [comment]
I found out now that we can't do this on Github! here is the link to that: mojombo/github-flavored-markdown#28
so I will close this.
