### ISSUE TITLE
Update ReadMe with GSSoC'21 guidelines 

### ISSUE THREAD

**Issue by Spring-dot** [girlscript/feminist-bible-phase-2#297]
### **Is your feature request related to a problem? Please Describe.**

Any new contributor (participant of GSSoC'21) should know all the guidelines, score table, FCFS etc when land to github repo.

### **Describe the solution you'd like**

Add a section in ReadMe with the heading 'GSSoC'21 guidelines' and all points will be covered in it.

### **Describe alternatives you've considered**

We can provide link to a new page with same guidelines for GSSoC.

**Comment by gauravdas014** [comment]
@Spring-dot We don't need this. So closing the issue.

**Comment by Spring-dot** [comment]
@gauravdas014 is there any issue unassigned? or what are project goals, how can I know the updates?

**Comment by gauravdas014** [comment]
@Spring-dot We need participants who can work on API integration and testing of the API. Moreover, you can check the frontend part, and if you find any bug can report it.
