### ISSUE TITLE
Add get all stories controller function

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#30]
Add a controller function to get all the stories. Add a route as well. Attach a screenshot of the response in the PR. (response from postman)

**Comment by nanda-mik** [comment]
I would like to work on this!

**Comment by gauravdas014** [comment]
Complete already allotted task first

**Comment by nanda-mik** [comment]
completed!

**Comment by gauravdas014** [comment]
There are many beginners. So I will be allotting this task to them. Don't worry you will be allotted some other task. Let us help everyone contribute and learn, especially the beginners

**Comment by nanda-mik** [comment]
fine!

**Comment by ruchikamuddinagiri** [comment]
I'd like to take this, if it's still open?

**Comment by gauravdas014** [comment]
Yes
