### ISSUE TITLE
Add email validator to adminModel and orgModel

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#300]
Use `validator` package for the implementation

**Comment by khushi935** [comment]
Can I work on this ?

**Comment by gauravdas014** [comment]
@khushi935 Go ahead

**Comment by khushi935** [comment]
Can you please suggest to me some references so that I can learn and do it?

**Comment by gauravdas014** [comment]
@khushi935 see userModel.js in the backend folder and you will get to know how to use validator

**Comment by khushi935** [comment]
![Screenshot (205)](https://user-images.githubusercontent.com/62712155/113867286-fcc73100-97cb-11eb-9ed6-4fcb713c5c40.png)
Please have a look.
I just added a validate line in both the files. This is correct? Or should I need to do something else?

**Comment by gauravdas014** [comment]
@khushi935 You need to also import the validator package at the top.

**Comment by khushi935** [comment]
okay done

> @khushi935 You need to also import the validator package at the top.

**Comment by gauravdas014** [comment]
@khushi935 If you are done, you can open a PR mentioning this issue
