### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#301]
We need detailed API documentation which will be helpful for those who will work on API integration. If you want to work on this issue, please share your ideas on how you will be proceeding.

**Comment by jhasuraj01** [comment]
@gauravdas014 I created the similar issue#302 please review that too and close anyone

**Comment by jhasuraj01** [comment]
@gauravdas014 I created the similar issue #302 😅. Please review that and close anyone
