### ISSUE TITLE
API Documentation is required for testing and reference

### ISSUE THREAD

**Issue by jhasuraj01** [girlscript/feminist-bible-phase-2#302]
### **Describe the solution you'd like**

There is a VS Code extension to deal with this problem

> Name: REST Client
> Id: humao.rest-client
> Description: REST Client for Visual Studio Code
> Version: 0.24.4
> Publisher: Huachao Mao
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

Below is the Screenshot of how this works
![image](https://user-images.githubusercontent.com/44930179/113662543-e9ca3900-96c5-11eb-850c-990788e696fd.png)

![image](https://user-images.githubusercontent.com/44930179/113662667-2e55d480-96c6-11eb-86e7-b538c4b2d4cb.png)

I think creating a common documentation like this will help working with API's more efficiently 

## Steps
- Step 1
  - [x] auth
  - [x] org
  - [x] projects
- Step 2
  - [x] admin
  - [x] user
- Step 3
  - [x] forum
  - [x] story

**Comment by gauravdas014** [comment]
@jhasuraj01 Does the .rest file work outside vs code? We will need something that can be opened from anywhere.

**Comment by jhasuraj01** [comment]
> @jhasuraj01 Does the .rest file work outside vs code? We will need something that can be opened from anywhere.

As ```.rest``` file is user defined, we no need to worry about it, I have selected this file extension because that extension supports it. Also, as this file contains raw request I guess it may work with curl too.

**Comment by gauravdas014** [comment]
@jhasuraj01 You can start the work. First, give a PR that shows your implementation, write for a single API, if anything is to be changed I will notify, then you can proceed with all the APIs

**Comment by jhasuraj01** [comment]
Can I created multiple PRs for each API as I would have to ready the whole code for each API

**Comment by gauravdas014** [comment]
@jhasuraj01 you can make around three PRs (one for admin & user, one forum and post, and one for the rest), if you give individual prs then it will be a Level2 PR, or you can submit a single PR which will be Level3, so whatever you prefer you can do.

**Comment by gauravdas014** [comment]
You can create sub-tasks in this issue(checkboxes) which will help in keeping track of the work done and left, which are under this issue.

**Comment by jhasuraj01** [comment]
> @jhasuraj01 you can make around three PRs (one for admin & user, one forum and post, and one for the rest), if you give individual prs then it will be a Level2 PR, or you can submit a single PR which will be Level3, so whatever you prefer you can do.

I haven't solved any level2 PR so I will go with 3PR option

**Comment by jhasuraj01** [comment]
@gauravdas014 I am stuck at Admin API

I guess currently newly created organization doesn't need any approval. If it has been implemented please lemme know. Also please tell me how shall I proceed further?

**Comment by jhasuraj01** [comment]
> @gauravdas014 I am stuck at Admin API
> 
> I guess newly created organization doesn't need any approval right now. If it has been implemented please lemme know. Also please tell me how shall I proceed further?

Shall I create new issue for this?

**Comment by gauravdas014** [comment]
@jhasuraj01 The current flow is: When the organization will sign up, we will keep a field let say `approved` to be false. Once the admin approvess we will simply mark this as true. When signing in we will need to verify if that boolean is true or false and we will have to allow accordingly. Currently, there is a controller function to approve the request, but I think there's some error currently, so we would have to fix it.

**Comment by gauravdas014** [comment]
@jhasuraj01 Can you verify the approval system and let me know?

**Comment by jhasuraj01** [comment]
```javascript
exports.createOrg = async (req, res) => {
  const { name, image, description, url } = req.body;
  let neworg;
  try {
    neworg = new Org({
      name,
      image,
      description,
      url,
    });
    console.log(neworg);
    await neworg.save();
  } catch (err) {
    console.log(err.message);
    return res.status(400).json({ msg: 'cannot register org' });
  }

  return res.status(201).json({
    data: {
      ...neworg._doc,
    },
  });
};
```

As you can see in the above code there is no such field called approved and declined

**Comment by jhasuraj01** [comment]
Also tell me, who is admin and what is its scope?

**Comment by gauravdas014** [comment]
This website is for the Organization named `Feminist Bible`. Assume the founders of `Feminist Bible` are the admins. Many other organizations can sign up to be a part of the `Feminist Bible`. So when those organizations will register the admins of the feminist bible will verify. So the admin refers to the `Feminist Bible` team.

**Comment by gauravdas014** [comment]
> ```js
> exports.createOrg = async (req, res) => {
>   const { name, image, description, url } = req.body;
>   let neworg;
>   try {
>     neworg = new Org({
>       name,
>       image,
>       description,
>       url,
>     });
>     console.log(neworg);
>     await neworg.save();
>   } catch (err) {
>     console.log(err.message);
>     return res.status(400).json({ msg: 'cannot register org' });
>   }
> 
>   return res.status(201).json({
>     data: {
>       ...neworg._doc,
>     },
>   });
> };
> ```
> 
> As you can see in the above code there is no such field called approved and declined

Please create a corresponding issue.

**Comment by jhasuraj01** [comment]
@gauravdas014 I have completed all the steps as mentioned in this and #307 issue and created 3 PRs of level2 in total kindly review each
