### ISSUE TITLE
Enhancement of UI of the Website [GSSoC 21]

### ISSUE THREAD

**Issue by vineetsingh0809** [girlscript/feminist-bible-phase-2#314]
I looked upon the website and want to enhance the UI of the website by changing some colors, adding some new buttons, modifying the CSS, and extra.
So could you assign e this issue...??

**Comment by Shivangi-ch** [comment]
Can you assign this to me?

**Comment by shashankmotruri** [comment]
@vineetsingh0809  Can Tou elaborate more?

**Comment by subhangi2731** [comment]
please assign me this
