### ISSUE TITLE
Issue in responsiveness of code-of-conduct page

### ISSUE THREAD

**Issue by vanshika-bhasin** [girlscript/feminist-bible-phase-2#342]
### **Explain what you did (Required)**
Opened the code of conduct page of feminist bible from the footer on its web-page.

### **Expected behavior (Required)**
Text in the web-page should have been aligned on the screen and all the points should be having same styling. 

### **Describe the bug (Required)**
The second point on code-of-conduct page does not align in same line with point 1.

Also, only point 1 is styled, other points do not have any background-color or any other styling.

![image](https://user-images.githubusercontent.com/42544468/115955218-e2eb5500-a512-11eb-86ca-9a74f600e695.png)

### **To Reproduce (Required)**

- Steps
1. Open the webpage.
2. Open the code of conduct page from the footer
![image](https://user-images.githubusercontent.com/42544468/115955568-e67fdb80-a514-11eb-8c34-5d50cfadab4c.png)
3. Scroll to the mentioned points.
![image](https://user-images.githubusercontent.com/42544468/115955593-14652000-a515-11eb-88e4-8443d95c8d0f.png)

4. It can be noticed that the second point on code-of-conduct page does not align in same line with point 1. Also, only point 1 is styled, other points do not have any background-color or any other styling.

Please assign me this issue. I'll do the necessary changes.

**Comment by gauravdas014** [comment]
@vanshika-bhasin Go ahead.

**Comment by vanshika-bhasin** [comment]
> @vanshika-bhasin Go ahead.

Thanks
