### ISSUE TITLE
Create Organization schema

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#43]
Create an organization schema. It should includes fields name, email, totalMembers, password. These fields are enough for now. We will add other fields later on.

**Comment by shagun0915** [comment]
Hey, I want to work on this issue

**Comment by gauravdas014** [comment]
@shagun0915 It's been a long time you were assigned this task. Need help?

**Comment by gauravdas014** [comment]
@shagun0915 Are you working?

**Comment by gauravdas014** [comment]
@ruchikamuddinagiri This task is still left , would you like to take this?
