### ISSUE TITLE
Create a controller function to get all organizations

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#63]

**Comment by joharikushagra** [comment]
#I want to work on this

**Comment by joharikushagra** [comment]
@gauravdas014  how to add up this? like there's no predefined model,route for the organization stuff

**Comment by gauravdas014** [comment]
The organization model is being created. For now assume there's an organization model. So create the function to get all organizations. Make the routes as well. Follow REST architecture.

**Comment by joharikushagra** [comment]
Okay!!
