### ISSUE TITLE
Make the approval system

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#66]
In our website some organizations will request for registration and soon they will register approved : false will be there in database.
So the admins should be able to see the approval requests. So that they can either accept or decline them. Make two other controller functions which will allow admin to accept the approval or to decline. Keep all these approval thing inside the adminController.js file

**Comment by ruchikamuddinagiri** [comment]
I'd like to work on this!

**Comment by ruchikamuddinagiri** [comment]
Could you elaborate the workflow? Will this require a new Organisation schema? If yes, which fields would be required?

**Comment by gauravdas014** [comment]
check issue #43
