### ISSUE TITLE
Project schema, get all projects , get all projects by organization controller function.

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#81]
In the site we are building , admins of an organization will add projects on which different members of the different organizations will collaborate on. We need the project title, project description, posted by ( the organization will be referenced), timestamps. For now just add these fields.   Make a controller function to see all the organizations. Another controller function to get all the projects organization wise.

**Comment by ruchikamuddinagiri** [comment]
I'd like to work on this!

**Comment by gauravdas014** [comment]
Please follow the response format of story controller functions, So that there is uniformity in the code

**Comment by ruchikamuddinagiri** [comment]
Sure!
