### ISSUE TITLE
Add new project

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#82]
Under admin controller create a function to add new project. See the issue of project schema for the fields required in the projects

**Comment by nanda-mik** [comment]
i would like to work on this!

**Comment by gauravdas014** [comment]
@nanda-mik I can't find you in the whatsApp group . Please join the whatsapp group asap. After that I will assign.

**Comment by nanda-mik** [comment]
Where is the link to join?

**Comment by gauravdas014** [comment]
In the Slack channel

**Comment by nanda-mik** [comment]
I am unaware about these things! Where i will get link to join slack?

**Comment by pratikbaid3** [comment]
I can work on this

**Comment by gauravdas014** [comment]
@nanda-mik Aren't you a part of GSSoC extended? If so you would have received the slack invitation .

**Comment by gauravdas014** [comment]
@pratikbaid3 I am assigning you

**Comment by nanda-mik** [comment]
@gauravdas014 No i am not a part of Gssoc. So, am i not eligible to contribute to any project under gssoc?

**Comment by gauravdas014** [comment]
@nanda-mik This project is only for those who are part of GSSoC extended.

**Comment by pratikbaid3** [comment]
@gauravdas014 Since the project schema is not done yet but the issue for it has been assigned, should I make the schema myself??

**Comment by gauravdas014** [comment]
Yes create a simple schema for now.
