### ISSUE TITLE
IsLogged in

### ISSUE THREAD

**Issue by gauravdas014** [girlscript/feminist-bible-phase-2#91]
Make a controller function under authController to check if a user is logged in.

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by gauravdas014** [comment]
Please make the necessary changes in the delete story function. Check the PR, I have mentioned

**Comment by Shubham-1105** [comment]
Ok

**Comment by Sudheer121** [comment]
Where will the token payload be for upcoming requests ?. Inside Authorization headers, cookies ?.

**Comment by gauravdas014** [comment]
Yes. It will be in cookies!

**Comment by gauravdas014** [comment]
@Sudheer121 Are you a part of GSSoC extended? I cannot see you in the whatsApp group

**Comment by Sudheer121** [comment]
No, is it needed ?

**Comment by Sudheer121** [comment]
I won't continue then.

**Comment by gauravdas014** [comment]
yeah!
